package com;

/**
* com/HelloWorldHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HelloWorld.idl
* Thursday, June 4, 2026 7:32:47 PM IST
*/

public final class HelloWorldHolder implements org.omg.CORBA.portable.Streamable
{
  public com.HelloWorld value = null;

  public HelloWorldHolder ()
  {
  }

  public HelloWorldHolder (com.HelloWorld initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.HelloWorldHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.HelloWorldHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.HelloWorldHelper.type ();
  }

}
