package com;


/**
* com/HelloWorld.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HelloWorld.idl
* Thursday, June 4, 2026 7:32:47 PM IST
*/

public interface HelloWorld extends HelloWorldOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HelloWorld
